const categoryActionTypes = {
    GET_ALL_CATEGORIES : "GET_ALL_CATEGORIES",
    CREATE_CATEGORY_START: "CREATE_CATEGORY_START",
    CREATE_CATEGORY_PROCCESING: "CREATE_CATEGORY_PROCCESING",
    CREATE_CATEGORY_SUCCESS : "CREATE_CATEGORY_SUCCESS",
    CREATE_CATEGORY_FAIL : "CREATE_CATEGORY_FAIL",
    
  };

  export default categoryActionTypes;