const orderActionType = {

    ADD_ORDER: "ADD_ORDER",
    ADD_ORDER_PROCESSING: "ADD_ORDER_PROCESSING",
    ADD_ORDER_SUCCESS: "ADD_ORDER_SUCCESS",
    AFTER_ORDER_SUCCESS: "AFTER_ORDER_SUCCESS",
    ADD_ORDER_FAIL: "ADD_ORDER_FAIL"
  };
  
  export default orderActionType;
  