const productActionTypes = {
    GET_ALL_PRODUCT : "GET_ALL_PRODUCT",
    CREATE_PRODUCT_START: "CREATE_PRODUCT_START",
    CREATE_PRODUCT_PROCCESING: "CREATE_PRODUCT_PROCCESING",
    CREATE_PRODUCT_SUCCESS : "CREATE_PRODUCT_SUCCESS",
    CREATE_PRODUCT_FAIL : "CREATE_PRODUCT_FAIL",
  };

  export default productActionTypes;