const adminActionTypes = {
    GET_ALL_USER : "GET_ALL_USER",
    CREATE_ASSISTANT_START: "CREATE_ASSISTANT_START",
    CREATE_ASSISTANT_PROCCESING: "CREATE_ASSISTANT_PROCCESING",
    CREATE_ASSISTANT_SUCCESS : "CREATE_ASSISTANT_SUCCESS",
    CREATE_ASSISTANT_FAIL : "CREATE_ASSISTANT_FAIL",
  };

  export default adminActionTypes;