const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',

    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    EMAIL_SIGN_IN_PROCESSING: 'EMAIL_SIGN_IN_PROCESSING',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',


    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',

    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_PROCESSING: 'SIGN_UP_PROCESSING',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    SIGN_UP_START: 'SIGN_UP_START',

    SAVE_USER_START: " SAVE_USER_START",
    SAVE_USER_PROCCESING: "SAVE_USER_PROCCESING",
    SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
    SAVE_USER__FAIL: "SAVE_USER__FAIL",
  };
  export default UserActionTypes;
  